### ISSUE TITLE
Textcolor not changing with themes

### ISSUE THREAD

**Issue by kay4ik** [kekland/equinox#12]
Hi,
EqText ist not changing the textcolor when the Theme of EquinoxApp changes to DarkMode...

Text is black in light Theme and black in dark theme. It should be white in dark Theme.

**Comment by kekland** [comment]
Hi! I've stopped maintaining **equinox**. It was more like a trial of implementing custom design system in Flutter. I am working on a new design system though to fix the bugs and the spaghetti-mess of **equinox**.
