### ISSUE TITLE
[BUG] Theme conflicts between EquinoxApp and EqLayout

### ISSUE THREAD

**Issue by kay4ik** [kekland/equinox#13]
Hi,
when the EquinoxApps theme is EqThemes.defaultLightTheme but the theme of the EqLayout below in Widget tree is EqThemes.defaultDarkTheme the Screen is dark in first build, but after first reload / rebuild the screen gets light and is never going dark again.

The theme of EqLayout should override the ThemeData of EquinoxApp.

**Comment by kekland** [comment]
#12
