### ISSUE TITLE
Android Studio Import Issue

### ISSUE THREAD

**Issue by JAICHANGPARK** [kekland/equinox#15]
![image](https://user-images.githubusercontent.com/19484515/68829821-4a319280-06ed-11ea-96d0-eec28a61473c.png)

**Comment by sarimk80** [comment]
You can change the import as:

`import 'package:equinox/equinox.dart' as eva;`
```

eva.EqLayout(
      appBar: eva.EqAppBar(
        title: widget.title,
      ),
```


you can also check out this repo for detail example:

https://github.com/sarimk80/flutter_equinox

**Comment by JAICHANGPARK** [comment]
@sarimk80  Thanks to Help
