### ISSUE TITLE
EquinoxApp not found

### ISSUE THREAD

**Issue by anisalibegic** [kekland/equinox#2]
`The method 'EquinoxApp' isn't defined for the class 'MyApp'.`

You forgot to add the `export 'package:equinox/components/global/equinox_app.dart';` to your exports in equinox.dart.

**Comment by kekland** [comment]
Whoops.

Will fix right away ;)
Thanks for notifying me.

**Comment by kekland** [comment]
I have pushed version v0.0.3 into pub, can you check if this issue has been resolved?

**Comment by anisalibegic** [comment]
I confirm everything is working fine now. Thanks and keep up the good work.
