### ISSUE TITLE
No Material widget found.

### ISSUE THREAD

**Issue by anisalibegic** [kekland/equinox#3]
```
No Material widget found.
TextField widgets require a Material widget ancestor.
```

**Comment by kekland** [comment]
It seems like I forgot to include Material widget into EqTextField. Will fix in the next version. Thanks for a report.

**Comment by kekland** [comment]
I have pushed version v0.0.3 to pub, can you check if everything is working now?

**Comment by anisalibegic** [comment]
I confirm everything is working fine now. Thanks and keep up the good work.
