### ISSUE TITLE
EqLayout and BottomNavigationBar

### ISSUE THREAD

**Issue by anisalibegic** [kekland/equinox#5]
**Describe the solution you'd like**
Option to have a bottom navigation bar in EqLayout just like in Scaffold. Also, it would be cool to have EqBottomNavigationBar that changes it's theme according to the EquinoxApp's theme.

**Describe alternatives you've considered**
Currently you could use BottomNavigationBar in Column.

**Comment by kekland** [comment]
Yes, that will be done soon. I will inform you here when it is released. Right now the focus is on the toast and dialog system.

![image](https://user-images.githubusercontent.com/14993994/60773516-6a8e8680-a128-11e9-89b7-1e65a247ae39.png)

**Comment by kekland** [comment]
Added `EqTabBar`, `EqTabBar.top()`, `EqLayout.bottomTabBar` and `EqTabBar.bottom()` in v0.1.3. Can you confirm that everything is working as expected?

**Comment by vedartm** [comment]
Can you add an Attribute `iconSize:` in `EqTabData` so that can change the size instead of a const 18.0. @kekland

**Comment by kekland** [comment]
@excogitatr Sure thing, I was thinking about more customization and theming. Will add in the next release.

**Comment by kekland** [comment]
@excogitatr Hey, I'm back from my short break, I've added `iconSize` in the latest release, can you check it its working?

**Comment by vedartm** [comment]
@kekland Tested the new version. Everything is working great.

**Comment by kekland** [comment]
@excogitatr Great to hear that :)
