### ISSUE TITLE
Optional EqAppBar title

### ISSUE THREAD

**Issue by anisalibegic** [kekland/equinox#6]
**Describe the solution you'd like**
I would love to have optional title in EqAppBar since sometimes I need only tabs (EqAppBar's bottom property) without the title.

**Comment by kekland** [comment]
Damn, I missclick a lot.

Added constructor `EqAppBar.withoutTitle(Widget bottom)` in v0.0.10.

**Comment by anisalibegic** [comment]
When using withoutTitle constructor there is some kind of bottom margin that pushes the EqLayout body. Body isn't right below EqAppBar. There is a gap between them.

**Comment by kekland** [comment]
Is it the same as #7?

**Comment by kekland** [comment]
Probably fixed with #8, closing now.
