### ISSUE TITLE
AppBar unused space

### ISSUE THREAD

**Issue by marcoagpegoraro** [kekland/equinox#7]
**Describe the bug**
This blank space is appearing in the bottom of the AppBar when i'm building to iOS, the github example project are doing the same thing.

**Screenshots**
![image](https://user-images.githubusercontent.com/29266005/60851631-50a58000-a1ca-11e9-8c7e-d1424798b8f9.png)

**Desktop**
 - OS: macOS 10.14.5
 - Flutter version 1.5.4-hotfix.2

**Smartphone**
 - Device: iPhone Xr
 - OS: iOS12.2

**Comment by kekland** [comment]
It seems like an issue with appbar's height calculation. Will look into that soon.

**Comment by kekland** [comment]
Should be fixed in v0.0.13, can you confirm that it is working properly now?

**Comment by marcoagpegoraro** [comment]
It's working properly now, thank you very much 
![image](https://user-images.githubusercontent.com/29266005/60903019-fe567480-a246-11e9-86e2-e0d978aebb1f.png)
