### ISSUE TITLE
Content scrolled under EqAppBar in Pixel 3XL Emulator

### ISSUE THREAD

**Issue by leodr** [kekland/equinox#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_1563457835](https://user-images.githubusercontent.com/39763575/61463356-838f0700-a974-11e9-84e1-7c719a1e8c3c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kekland** [comment]
Hi!

Sorry, but I can't seem to find a bug or error in the image. Do you mean the empty space between the top of the screen and appbar?

**Comment by kekland** [comment]
Oh, I see it now, sorry.

I will test it and see where's the problem. Seems like something is wrong with EqLayout's handling of the status bar.

**Comment by kekland** [comment]
Should be fixed in v0.3.2, can you check that everything is working as expected?

**Comment by leodr** [comment]
> Should be fixed in v0.3.2, can you check that everything is working as expected?

Well, the first bug is fixed, but it created another one ;)

In the main list there is space between the AppBar and the content.

![Screenshot_1563556172](https://user-images.githubusercontent.com/39763575/61552697-d2ae6800-aa58-11e9-9d49-316170d49bad.png)

**Comment by kekland** [comment]
Dang it, strange that there are no issues on my galaxy s8 :/

Will fix tomorrow

**Comment by leodr** [comment]
> Dang it, strange that there are no issues on my galaxy s8 :/
> 
> Will fix tomorrow

I think it has something to do with the Pixel 3 XL having that giant notch. You can always test in a Pixel 3 XL Android Emulator.

**Comment by kekland** [comment]
Oh, I found the issue. Yes, it was hard to see it on my Galaxy due to small status bar size, but the problem was in how ListView handles paddings. As written in the ListView:

```
By default, [ListView] will automatically pad the list's scrollable
extremities to avoid partial obstructions indicated by [MediaQuery]'s
padding. To avoid this behavior, override with a zero [padding] property.
```

So, that should be fixed in the QA app now in the latest commit.
