### ISSUE TITLE
Question: Are third party widgets still compatible?

### ISSUE THREAD

**Issue by tinusg** [kekland/equinox#9]
I don't fully understand what the consequences of switching to equinox will be. Are third party widgets, like image picker, still compatible? Is it possible to use or fall back to Material or Cupertino style widgets if needed?

**Comment by kekland** [comment]
Hi! Yes, Equinox uses MaterialApp internally, and I think third-party widgets should be ok (I'm using image picker in my own app, and it works just fine).

**Comment by tinusg** [comment]
Thanks!
